/**:
  ros__parameters:
    cam_base_topic: camera/image_color
    output_frame: 'base_link'

    marker_dict: 4X4_50

    publish_tf: true
    marker_size: 0.15

    aruco:
      adaptiveThreshWinSizeMin: 3
      adaptiveThreshWinSizeMax: 23
      adaptiveThreshWinSizeStep: 10
